[workspace]
resolver = "2"
members = [
    "crates/mir-formats",
    "crates/mir-atlas",
    "crates/mir-pack",
    "crates/protocol",
    "crates/sim",
    "server",
    "client",
    "launcher",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/lu020218/mirforge"

[workspace.lints.clippy]
all = "warn"

# Bevy 官方建议: 开发期给依赖开优化, 否则调试构建帧率过低
[profile.dev.package."*"]
opt-level = 3
